"""Initial setup

Revision ID: ac29ffb832e6
Revises: 
Create Date: 2026-04-28 11:26:25.591635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac29ffb832e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('video_filename', sa.String(length=255), nullable=True),
    sa.Column('quiz_json', sa.Text(), nullable=True),
    sa.Column('quiz_score', sa.Integer(), nullable=True),
    sa.Column('quiz_total', sa.Integer(), nullable=True),
    sa.Column('is_favorite', sa.Integer(), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=512), nullable=True),
    sa.Column('performance_analysis', sa.Text(), nullable=True),
    sa.Column('quiz_results', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_history_email'), 'search_history', ['email'], unique=False)
    op.create_index(op.f('ix_search_history_username'), 'search_history', ['username'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_search_history_username'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_email'), table_name='search_history')
    op.drop_table('search_history')
    # ### end Alembic commands ###
